### ISSUE TITLE
Formatter doesn't follow prisma conventions

### ISSUE THREAD

**Issue by sidharthv96** [zenstackhq/zenstack#381]
**Description and expected behavior**
The formatter differs from prisma in 2 ways

1. Removes intentional blank lines
2. Removes the column wise spacing of types

This is not a major issue, but would be nice to have and will reduce the changes with prisma schema where projects already have existing prisma schema. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10703445/235990791-77c06106-ff56-4cf7-9c08-f4e4a0276483.png)
![image](https://user-images.githubusercontent.com/10703445/235990866-9fa11791-b510-4ad2-b4fe-c1c52495516d.png)

**Environment (please complete the following information):**

-   ZenStack version: [e.g., 1.0.0-alpha.50]
-   Prisma version: [e.g., 4.10.0]
-   Database type: [e.g. Postgresql]

**Additional context**

**Comment by ymc9** [comment]
@jiashengguo FYI and I especially hate the behavior of removing blank lines 😄

**Comment by sidharthv96** [comment]
I think the easiest way would be to 

1. Keep blank lines 
2. Add one blank line to top and bottom of newly added `zenstack_*` columns
3. Use prisma's formatter on the schema after generation

This means no need to spend much time on Zenstack formatter right now, and would keep the changes in prisma schema minimal. 

Had a nice chat with @jiashengguo :)

**Comment by jiashengguo** [comment]
Fixed by #400.

@sidharthv96  It has been included in the recent release v1.0.0-alpha.114 and VSCode extension. 

BTW, To not affect other users, we added a flag to control whether or not to format the generated prisma schema. So you need to add the below plugin code snippet in your schema file.

```
plugin prisma {
    provider = '@core/prisma'
    format = true
}
```

**Comment by sidharthv96** [comment]
@jiashengguo thank you!

The formatting issue is fixed, but the blank lines are sadly still being removed.

https://github.com/zenstackhq/zenstack/pull/400/commits/4d7699f05e2d64012dcf2b50e16a060b7e8609df#r1187042502

**Comment by juni0r** [comment]
I'm still seeing this behavior with zenstack@1.8.2 and VSCode plugin v1.7.0. Am I missing something here?

**Comment by ymc9** [comment]
> I'm still seeing this behavior with zenstack@1.8.2 and VSCode plugin v1.7.0. Am I missing something here?
> 
> `EDIT` I didn't realize this issue was about the generated prisma schema which does get formatted properly. I was referring to the VSCode extension which doesn't provide syntax highlighting and formatting for `.zmodel` files in the way the Prisma extension does for schemas.

Hi @juni0r , there's a feature request scheduled for V2 here: https://github.com/zenstackhq/zenstack/issues/885
