### ISSUE TITLE
.zenstack directory not created when using pnpm

### ISSUE THREAD

**Issue by abdullahahmeda** [zenstackhq/zenstack#647]
**Description and expected behavior**
When using `pnpm`, `.zenstack` is not found in `node_modules`. This folder contains some zod schemas I need for my project.

**Environment (please complete the following information):**
This issue isn't related to a specific version.

**Comment by abdullahahmeda** [comment]
For now, to fix this issue, `npm` should be used instead of `pnpm`

**Comment by ymc9** [comment]
Fixed in [1.0.0-beta.21](https://github.com/zenstackhq/zenstack/releases/tag/v1.0.0-beta.21)

**Comment by abdullahahmeda** [comment]
This issue is not fixed yet. The following error is thrown
```
Module not found: Package path ./zod/objects is not exported from package /home/abdullah/projects/dar-management/node_modules/@zenstackhq/runtime (see exports field in /home/abdullah/projects/dar-management/node_modules/@zenstackhq/runtime/package.json)
```

I will fix it now
